# Generated by Django 3.0.1 on 2020-01-01 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20200101_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='useremail',
            new_name='usermail',
        ),
    ]
